---
- name: create temporary mbox directory
  tempfile:
    state: directory
    prefix: mbox
    suffix: deploy
  register: mbox_dir

- include_tasks: cert.yml

- block:
    - name: mbox.pvc
      k8s_info:
        api_version: v1
        kind: PersistentVolumeClaim
        namespace: "{{ meta.namespace }}"
        name: "{{ mbox_koji_pvc_name }}"
      register: k8s_mbox_pvc_query
    - k8s:
        state: present
        wait: true
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            namespace: "{{ meta.namespace }}"
            name: "{{ mbox_koji_pvc_name }}"
            labels:
              app: mbox
          spec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: "{{ mbox_koji_pvc_size }}"
            selector:
              matchLabels:
                app: mbox
      when: k8s_mbox_pvc_query.resources|length == 0
