---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint roles/
platforms:
  - name: kind-test-local
    groups:
      - k8s
    image: bsycorp/kind:latest-1.16
    privileged: true
    override_command: false
    exposed_ports:
      - 8443/tcp
      - 10080/tcp
    published_ports:
      - 0.0.0.0:${TEST_CLUSTER_PORT:-10443}:8443/tcp
    pre_build_image: true
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}:/build:Z
provisioner:
  name: ansible
  log: true
  lint: |
    ansible-lint .
  inventory:
    group_vars:
      all:
        namespace: ${TEST_NAMESPACE:-osdk-test}
        operator_image: apps.fedoraproject.org/mbox-operator:testing
    host_vars:
      localhost:
        ansible_python_interpreter: '{{ ansible_playbook_python }}'
        config_dir: ${MOLECULE_PROJECT_DIRECTORY}/config
        samples_dir: ${MOLECULE_PROJECT_DIRECTORY}/config/samples
        components_dir: ${MOLECULE_PROJECT_DIRECTORY}/../components
        operator_image: ${OPERATOR_IMAGE:-"apps.fedoraproject.org/mbox-operator:testing"}
        operator_pull_policy: ${OPERATOR_PULL_POLICY:-"IfNotPresent"}
        kustomize: ${KUSTOMIZE_PATH:-kustomize}
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
  env:
    K8S_AUTH_KUBECONFIG: /tmp/molecule/kind-test-local/kubeconfig
    KUBECONFIG: /tmp/molecule/kind-test-local/kubeconfig
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
    KIND_PORT: '${TEST_CLUSTER_PORT:-10443}'
  playbooks:
    destroy: destroy.yml
    verify: ../default/verify.yml
scenario:
  name: test-local
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
verifier:
  name: ansible
  lint: |
    flake8
