---
- name: Install Operator SDK system dependencies
  dnf:
    name: [
            golang,
            docker,
            kubernetes-client,
            conntrack-tools
          ]
    state: present

- name: Install Operator SDK python dependencies
  pip:
    name: [
      'ansible',
      'flake8',
      'ansible-lint',
      'molecule',
      'molecule[docker]',
      'docker',
      'kubernetes',
      'jmespath',
      'openshift',
      'molecule-docker'
    ]

- name: Create docker group
  group:
    name: docker
    state: present
  become: yes

- name: Ensure user is added to docker group
  user:
    name: "{{ dev_username }}"
    groups: ['docker']
    append: yes
  become: yes

- name: Reset ssh connection to allow user changes to affect 'current login user'
  meta: reset_connection

- name: Start docker
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker

# I don't like to do this, but the manually installed minikube needs to many SELinux changes
- name: Set SELinux to permissive
  selinux:
    policy: targeted
    state: permissive

# Install origin-clients
- name: Download oc binary
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
    dest: /tmp/

- name: Extract oc binary
  unarchive:
    src: /tmp/oc.tar.gz
    dest: /usr/local/bin
    remote_src: yes

# Install minikube
- name: Download minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-{{minikube_version}}.x86_64.rpm
    dest: /tmp/

- name: Install minikube
  dnf:
    name: /tmp/minikube-{{minikube_version}}.x86_64.rpm
    state: present

# We are running inside VM, so set default driver to none
- name: Set minikube default driver to none
  command: minikube config set driver docker

- name: Start minikube cluster
  command: minikube start --force

- name: Make .kube folder
  file:
    path: /.kube
    state: directory
  become: yes

- name: Get minkube config
  command: "minikube kubectl config view"
  register: output

- name: Copy config content
  copy:
    content: "{{ output.stdout }}"
    dest: /.kube/config
  become: yes

- name: Enable ingress addon for minikube
  command: minikube addons enable ingress

# "Install" the operator SDK
- name: Retrieve binary
  get_url:
    url: https://github.com/operator-framework/operator-sdk/releases/download/v{{operator_sdk_version}}/operator-sdk-v{{operator_sdk_version}}-x86_64-linux-gnu
    dest: /tmp/

- name: Move binary to correct location
  copy:
    src: /tmp/operator-sdk-v{{operator_sdk_version}}-x86_64-linux-gnu
    dest: /usr/local/bin/operator-sdk
    mode: '0755'
    remote_src: yes
