---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - community.kubernetes
    - operator_sdk.util

  tasks:
    - name: Create Namespace
      k8s:
        api_version: v1
        kind: Namespace
        name: '{{ namespace }}'
        wait: true

    - name: Deploy postgres
      k8s:
        src: "{{ components_dir }}/psql/{{ item }}"
        namespace: "{{ namespace }}"
        state: present
        wait: true
      with_items:
        - 0-secret.yaml
        - 1-pvc.yaml
        - 2-deployment.yaml
        - 3-service.yaml

    - name: Deploy kerberos
      k8s:
        src: "{{ components_dir }}/kerberos/{{ item }}"
        namespace: "{{ namespace }}"
        state: present
        wait: true
      with_items:
        - 0-service.yaml
        - 1-configmap.yaml
        - 2-deployment.yaml
        
    - name: Create RabbitMQ ConfigMap
      k8s:
        src: "{{ components_dir }}/rabbitmq/1-app.secret.yaml"
        namespace: "{{ namespace }}"
        state: present
        wait: true

    - import_tasks: kustomize.yml
      vars:
        state: present
