---
- name: Verify
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
  tasks:
      - block:
          - name: mbox.secret.root_ca
            k8s_info:
              api_version: v1
              kind: Secret
              namespace: "{{ namespace }}"
              name: mbox-koji-root-ca
            register: k8s_secrets
          - assert:
              that:
                - k8s_secrets.resources|length == 1
                - k8s_secrets.resources[0].metadata.labels['app'] == 'mbox'
                - "'ca_req.pem' in k8s_secrets.resources[0].data"
                - "'ca_cert.pem' in k8s_secrets.resources[0].data"
                - "'ca_key.pem' in k8s_secrets.resources[0].data"
