# Disaled until we have a real CI kubernetes cluster
# - job:
#     name: test-cluster
#     run: ci/test-cluster.yml
#     nodeset: fedora-30-vm-medium
- job:
    name: test-local
    run: ci/test-local.yml
    nodeset: fedora-36-vm-medium
- job:
    name: test-docs
    run: ci/test-docs.yml
    nodeset: fedora-36-vm
- job:
    name: test-lint
    run: ci/test-default.yml
    nodeset: fedora-36-vm
- project:
    check:
      jobs:
        # - test-cluster
        - test-local
        - test-docs
        - test-lint

