- job:
    name: test-cluster
    run: ci/test-cluster.yml
    nodeset: fedora-30-vm
- job:
    name: test-local
    run: ci/test-local.yml
    nodeset: fedora-30-vm
- job:
    name: test-docs
    run: ci/test-docs.yml
    nodeset: fedora-30-vm
- project:
    check:
      jobs:
        - test-cluster
        - test-docs

