apiVersion: v1
kind: DeploymentConfig
metadata:
  name: identity
  labels:
    app: identity
    service: identity
spec:
  replicas: {{ replicas }}
  selector:
    deploymentconfig: identity
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: identity
        deploymentconfig: identity
    spec:
      containers:
      - name: identity
        image: identity:latest
        ports:
        - containerPort: 8443
        resources: {}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/ipsilon-cfg
          readOnly: true
        - name: httpdir-volume
          mountPath: /httpdir
        - name: cacert-volume
          mountPath: /etc/cacert
          readOnly: true
        - name: service-cert-volume
          mountPath: /etc/servicecert
          readOnly: true
        - name: etcipsilon
          mountPath: /etc/ipsilon
        readinessProbe:
          timeoutSeconds: 10
          initialDelaySeconds: 5
          httpGet:
            port: 8443
            scheme: HTTPS
        livenessProbe:
          timeoutSeconds: 10
          initialDelaySeconds: 30
          httpGet:
            port: 8443
            scheme: HTTPS
      volumes:
      - name: config-volume
        configMap:
          name: identity-configmap
      - name: cacert-volume
        secret:
          secretName: cacert
      - name: service-cert-volume
        secret:
          secretName: cert-identity
      - name: httpdir-volume
        emptyDir: {}
      - name: etcipsilon
        persistentVolumeClaim:
          claimName: etcipsilon
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - identity
      from:
        kind: ImageStreamTag
        name: identity:latest
        namespace: {{ project_name }}
    type: ImageChange
  - type: ConfigChange
