apiVersion: v1
kind: Service
metadata:
  name: identity
  labels:
    app: identity
    service: identity
spec:
  ports:
    - name: web
      port: 8443
      targetPort: 8443
  selector:
    deploymentconfig: identity
