# permissions for end users to view mbkojibuilders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mbkojibuilder-viewer-role
rules:
- apiGroups:
  - apps.fedoraproject.org
  resources:
  - mbkojibuilders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.fedoraproject.org
  resources:
  - mbkojibuilders/status
  verbs:
  - get
