# permissions for end users to edit mbkojibuilders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mbkojibuilder-editor-role
rules:
- apiGroups:
  - apps.fedoraproject.org
  resources:
  - mbkojibuilders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.fedoraproject.org
  resources:
  - mbkojibuilders/status
  verbs:
  - get
