# permissions for end users to edit mbkojihubs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mbkojihub-editor-role
rules:
- apiGroups:
  - apps.fedoraproject.org
  resources:
  - mbkojihubs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.fedoraproject.org
  resources:
  - mbkojihubs/status
  verbs:
  - get
