# permissions for end users to view mbkojiras.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mbkojira-viewer-role
rules:
- apiGroups:
  - apps.fedoraproject.org
  resources:
  - mbkojiras
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.fedoraproject.org
  resources:
  - mbkojiras/status
  verbs:
  - get
