# permissions for end users to view mbmbsfrontends.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mbmbsfrontend-viewer-role
rules:
- apiGroups:
  - apps.fedoraproject.org
  resources:
  - mbmbsfrontends
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.fedoraproject.org
  resources:
  - mbmbsfrontends/status
  verbs:
  - get
