# permissions for end users to edit mbmbsfrontends.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mbmbsfrontend-editor-role
rules:
- apiGroups:
  - apps.fedoraproject.org
  resources:
  - mbmbsfrontends
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.fedoraproject.org
  resources:
  - mbmbsfrontends/status
  verbs:
  - get
