# permissions for end users to view mbmbsbackends.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mbmbsbackend-viewer-role
rules:
- apiGroups:
  - apps.fedoraproject.org
  resources:
  - mbmbsbackends
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.fedoraproject.org
  resources:
  - mbmbsbackends/status
  verbs:
  - get
