# permissions for end users to view mboxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mbox-viewer-role
rules:
- apiGroups:
  - apps.fedoraproject.org
  resources:
  - mboxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.fedoraproject.org
  resources:
  - mboxes/status
  verbs:
  - get
