---
- name: Create the apps.fedoraproject.org/v1alpha1.MBKojiBuilder
  k8s:
    state: present
    namespace: '{{ namespace }}'
    definition: "{{ lookup('template', '/'.join([samples_dir, cr_file])) | from_yaml }}"
    wait: yes
    wait_timeout: 300
    wait_condition:
      type: Running
      reason: Successful
      status: "True"
  vars:
    cr_file: 'apps_v1alpha1_mbkojibuilder.yaml'

- block:
    - name: 'TEST: kojibuilder.configmap'
      k8s_info:
        api_version: v1
        kind: ConfigMap
        namespace: "{{ namespace }}"
        name: koji-builder-configmap
      register: koji_configmap
    - assert:
        that:
          - koji_configmap.resources|length == 1
          - koji_configmap.resources[0].metadata.labels['app'] == 'koji-builder'
          - "'kojid.conf' in koji_configmap.resources[0].data"

- block:
    - name: 'TEST: kojibuilder.secret.client-cert'
      k8s_info:
        api_version: v1
        kind: Secret
        namespace: "{{ namespace }}"
        name: koji-builder-client-cert
      register: kojibuilder_client_secrets
    - assert:
        that:
          - kojibuilder_client_secrets.resources|length == 1
          - kojibuilder_client_secrets.resources[0].metadata.labels['app'] == 'koji-builder'
          - "'tls.crt' in kojibuilder_client_secrets.resources[0].data"
          - "'tls.key' in kojibuilder_client_secrets.resources[0].data"

- block:
    - name: 'TEST: kojibuilder.pod deployment'
      k8s_info:
        api_version: v1
        kind: Pod
        namespace: "{{ namespace }}"
        label_selectors:
          - app = koji-builder
      register: pods
    - assert:
        that:
          - pods.resources|length == 1
          - pods.resources[0].metadata.labels['app'] == 'koji-builder'
