---
- name: Create the apps.fedoraproject.org/v1alpha1.MBKojira
  k8s:
    state: present
    namespace: '{{ namespace }}'
    definition: "{{ lookup('template', '/'.join([samples_dir, cr_file])) | from_yaml }}"
    wait: yes
    wait_timeout: 300
    wait_condition:
      type: Running
      reason: Successful
      status: "True"
  vars:
    cr_file: 'apps_v1alpha1_mbkojira.yaml'

- block:
    - name: 'TEST: kojira.configmap'
      k8s_info:
        api_version: v1
        kind: ConfigMap
        namespace: "{{ namespace }}"
        name: kojira-config
      register: kojira_configmap
    - assert:
        that:
          - kojira_configmap.resources|length == 1
          - kojira_configmap.resources[0].metadata.labels['app'] == 'kojira'
          - "'kojira.conf' in kojira_configmap.resources[0].data"

- block:
    - name: 'TEST: kojira.secret.client-cert'
      k8s_info:
        api_version: v1
        kind: Secret
        namespace: "{{ namespace }}"
        name: kojira-client-cert
      register: kojira_client_secrets
    - assert:
        that:
          - kojira_client_secrets.resources|length == 1
          - kojira_client_secrets.resources[0].metadata.labels['app'] == 'kojira'
          - "'client.pem' in kojira_client_secrets.resources[0].data"

- block:
    - name: 'TEST: kojira.deployment'
      k8s_info:
        api_version: v1
        kind: Deployment
        namespace: "{{ namespace }}"
        name: kojira
      register: kojira_deployments
    - k8s_info:
        api_version: v1
        kind: Pod
        namespace: "{{ namespace }}"
        label_selectors:
          - app = kojira
      register: kojira_pods
    - assert:
        that:
          - kojira_deployments.resources|length == 1
          - kojira_deployments.resources[0].metadata.labels['app'] == 'kojira'
    - assert:
        that:
          - kojira_pods.resources|length == 1
          - kojira_pods.resources[0].metadata.labels['app'] == 'kojira'
