apiVersion: apps/v1
kind: Deployment
metadata:
  name: mbox-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mbox-operator
  template:
    metadata:
      labels:
        name: mbox-operator
    spec:
      serviceAccountName: mbox-operator
      containers:
        - name: ansible
          command:
            - /usr/local/bin/ao-logs
            - /tmp/ansible-operator/runner
            - stdout
          # Replace this with the built image name
          image: quay.io/fedora/mbox-operator:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /tmp/ansible-operator/runner
              name: runner
              readOnly: true
        - name: operator
          # Replace this with the built image name
          image: quay.io/fedora/mbox-operator:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /tmp/ansible-operator/runner
              name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mbox-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}
