---
- name: create temporary kojira directory
  tempfile:
    state: directory
    prefix: kojira
    suffix: deploy
  register: kojira_dir

- include_tasks: cert.yml

- block:
    - name: ensure kojira configmap
      template:
        src: kojira.configmap.yaml.j2
        dest: "{{ kojira_dir.path }}/kojira.configmap.yaml"
    - k8s:
        state: present
        wait: true
        namespace: "{{ meta.namespace }}"
        src: "{{ kojira_dir.path }}/kojira.configmap.yaml"

- block:
    - name: retrieve and set shared pvc name var
      k8s_info:
        api_version: apps.fedoraproject.org/v1alpha1
        kind: Mbox
        namespace: "{{ meta.namespace }}"
        name: "{{ kojira_builder_mbox }}"
      register: k8s_mboxes
    - fail:
        msg: "Failed to find mbox {{ kojira_builder_mbox }} in namespace {{ meta.namespace }}"
      when: k8s_mboxes.resources|length == 0
    - set_fact:
        kojira_shared_pvc: "{{ k8s_mboxes.resources[0].spec.koji_pvc_name }}"
  when: kojira_builder_mbox|length > 0

- block:
    - name: ensure kojira deployment
      template:
        src: kojira.deployment.yaml.j2
        dest: "{{ kojira_dir.path }}/kojira.deployment.yaml"
    - k8s:
        state: present
        wait: true
        namespace: "{{ meta.namespace }}"
        src: "{{ kojira_dir.path }}/kojira.deployment.yaml"

- name: cleanup
  file:
    path: "{{ kojira_dir.path }}"
    state: absent
