---
- name: Build Operator in Kubernetes docker container
  hosts: k8s
  vars:
    image_name: apps.fedoraproject.org/mbox-operator:testing
    dockerfile_path: '{{ playbook_dir }}/../../build/Dockerfile'
  tasks:
    # using command so we don't need to install any dependencies
    - name: Get existing image hash
      command: docker images -q {{ image_name }}
      register: prev_hash
      changed_when: false

    - name: Build Operator Image
      command: docker build -f {{ dockerfile_path }} -t {{ image_name }} '{{ playbook_dir }}/../../'
      register: build_cmd
      changed_when: not prev_hash.stdout or (prev_hash.stdout and prev_hash.stdout not in ''.join(build_cmd.stdout_lines[-2:]))

- import_playbook: '{{ playbook_dir }}/../default/converge/converge_mbox.yml'
- import_playbook: '{{ playbook_dir }}/../default/converge/converge_koji-hub.yml'
- import_playbook: '{{ playbook_dir }}/../default/converge/converge_mbs-backend.yml'
- import_playbook: '{{ playbook_dir }}/../default/converge/converge_mbs-frontend.yml'
