---
- name: Converge
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
    pull_policy: Never
    REPLACE_IMAGE:  apps.fedoraproject.org/mbox-operator:testing
    custom_resource: "{{ lookup('file', '/'.join([deploy_dir, 'crds/apps.fedoraproject.org_v1alpha1_mbox_cr.yaml'])) | from_yaml }}"

  tasks:
    - import_tasks: '{{ playbook_dir }}/tasks/mbox.yml'

- import_playbook: '{{ playbook_dir }}/../../default/asserts/mbox.yml'
