apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    build: koji-hub
  name: koji-hub
spec:
  runPolicy: Serial
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: koji-hub:latest
  source:
    secrets:
    - secret:
        name: cacert
      destinationDir: cacert
    dockerfile: |-
      # Apache on centos7 keeps throwing segfaults...
      #FROM centos:7
      FROM fedora:latest
      COPY cacert/cert /etc/pki/ca-trust/source/anchors/mbox_ca.pem
      RUN update-ca-trust
      RUN yum install --setopt tsflags= -y koji koji-hub koji-web koji-hub-plugins httpd mod_ssl postgresql fedmsg
      RUN curl https://infrastructure.fedoraproject.org/cgit/ansible.git/plain/roles/koji_hub/templates/fedmsg-koji-plugin.py -o /usr/lib/koji-hub-plugins/fedmsg-koji-plugin.py
      RUN rm -f /etc/kojiweb/web.conf
      RUN ln -s /etc/koji-hub/kojiweb.conf /etc/kojiweb/web.conf
      RUN update-ca-trust
      ENV USER=openshift
      EXPOSE 8443
      ENTRYPOINT bash /etc/koji-hub/start.sh
